---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static Website: combining S3, CloudFront and Route53, a cloudonaut.io template'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentZoneStack
    - Label:
        default: 'Lambda@Edge Parameters'
      Parameters:
      - LambdaEdgeSubdirectoriesLambdaVersionArn
    - Label:
        default: 'CloudFront Parameters'
      Parameters:
      - IndexDocument
    - Label:
        default: 'DNS Parameters'
      Parameters:
      - DomainName
      - RedirectDomainName
      - HostedZoneId
    - Label:
        default: 'SSL/TLS Parameters'
      Parameters:
      - CertificateType
      - ExistingCertificate
Parameters:
  ParentZoneStack:
    Description: 'Optional stack name of parent zone stack based on vpc/zone-*.yaml template.'
    Type: String
    Default: ''
  LambdaEdgeSubdirectoriesLambdaVersionArn:
    Description: 'Optional version ARN of Lambda@Edge function based on static-website/lambdaedge-index-document.yaml template and exposed as output LambdaVersionArn.'
    Type: String
    Default: ''
  IndexDocument:
    Description: 'The name of the index document for the website.'
    Type: String
    Default: 'index.html'
  DomainName:
    Description: 'The primary domain name of the static website (e.g. widdix.de).'
    Type: String
  RedirectDomainName:
    Description: 'Optional domain name redirecting to DomainName (e.g. www.widdix.de).'
    Type: String
    Default: ''
  CertificateType:
    Description: 'Indicates whether to use the certificate from the AWS Certificate Manager or AWS Identity and Access Management. CreateAcmCertificate only works in the us-east-1 region.'
    Type: String
    Default: IamCertificateId
    AllowedValues:
    - AcmCertificateArn
    - IamCertificateId
    - CreateAcmCertificate
  ExistingCertificate:
    Description: 'Optional ACM Certificate ARN or IAM Certificate ID. Must be created in the us-east-1 region!'
    Type: String
    Default: ''
  HostedZoneId:
    Description: 'Deprecated in v7, will be removed in v8, use ParentZoneStack instead! The Id of the hosted zone managed by AWS Route53.'
    Type: String
    Default: ''
Conditions:
  HasRedirectDomainName: !Not [!Equals [!Ref RedirectDomainName, '']]
  HasAcmCertificateArn: !Equals [!Ref CertificateType, 'AcmCertificateArn']
  HasIamCertificateId: !Equals [!Ref CertificateType, 'IamCertificateId']
  HasCreateAcmCertificate: !Equals [!Ref CertificateType, 'CreateAcmCertificate']
  HasZone: !Not [!Equals [!Ref ParentZoneStack, '']]
  HasNotZone: !Equals [!Ref ParentZoneStack, '']
  HasRedirectDomainNameAndHasZone: !And [!Condition HasRedirectDomainName, !Condition HasZone]
  HasRedirectDomainNameAndHasNotZone: !And [!Condition HasRedirectDomainName, !Condition HasNotZone]
  HasLambdaEdgeSubdirectoriesLambdaVersionArn: !Not [!Equals [!Ref LambdaEdgeSubdirectoriesLambdaVersionArn, '']]
Resources:
  Certificate:
    Condition: HasCreateAcmCertificate
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions: !If
      - HasRedirectDomainName
      - - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
        - DomainName: !Ref RedirectDomainName
          ValidationDomain: !Ref DomainName
      - - DomainName: !Ref DomainName
          ValidationDomain: !Ref DomainName
      SubjectAlternativeNames: !If [HasRedirectDomainName, [!Ref RedirectDomainName], []]
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Action:
          - 's3:GetObject'
          Effect: Allow
          Resource:
          - !Sub 'arn:aws:s3:::${S3Bucket}/*'
          Principal:
            CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref DomainName
        Comment: !Ref DomainName
        Origins:
        - DomainName: !GetAtt 'S3Bucket.DomainName'
          Id: s3origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          LambdaFunctionAssociations: !If
          - HasLambdaEdgeSubdirectoriesLambdaVersionArn
          - - EventType: 'origin-request'
              LambdaFunctionARN: !Ref LambdaEdgeSubdirectoriesLambdaVersionArn
          - !Ref 'AWS::NoValue'
          TargetOriginId: s3origin
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: !Ref IndexDocument
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !If [HasCreateAcmCertificate, !Ref Certificate, !If [HasAcmCertificateArn, !Ref ExistingCertificate, !Ref 'AWS::NoValue']]
          IamCertificateId: !If [HasIamCertificateId, !Ref ExistingCertificate, !Ref 'AWS::NoValue']
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1
  Route53Record:
    Type: 'AWS::Route53::RecordSetGroup'
    Condition: HasNotZone
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
  Route53RecordV2:
    Type: 'AWS::Route53::RecordSetGroup'
    Condition: HasZone
    Properties:
      HostedZoneId:
        'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneId'
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
  S3BucketRedirect:
    Condition: HasRedirectDomainName
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref RedirectDomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName
          Protocol: https
  CloudFrontDistributionRedirect:
    Condition: HasRedirectDomainName
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref RedirectDomainName
        Comment: !Ref RedirectDomainName
        Origins:
        - DomainName: !GetAtt 'S3BucketRedirect.DomainName'
          Id: s3origin
          CustomOriginConfig:
            OriginProtocolPolicy: 'http-only'
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: s3origin
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        HttpVersion: http2
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !If [HasCreateAcmCertificate, !Ref Certificate, !If [HasAcmCertificateArn, !Ref ExistingCertificate, !Ref 'AWS::NoValue']]
          IamCertificateId: !If [HasIamCertificateId, !Ref ExistingCertificate, !Ref 'AWS::NoValue']
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1
  Route53RecordRedirect:
    Condition: HasRedirectDomainNameAndHasNotZone
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref RedirectDomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
          DNSName: !GetAtt 'CloudFrontDistributionRedirect.DomainName'
  Route53RecordRedirectV2:
    Condition: HasRedirectDomainNameAndHasZone
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId:
        'Fn::ImportValue': !Sub '${ParentZoneStack}-HostedZoneId'
      RecordSets:
      - Name: !Ref RedirectDomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
          DNSName: !GetAtt 'CloudFrontDistributionRedirect.DomainName'
Outputs:
  TemplateID:
    Description: 'cloudonaut.io template id.'
    Value: 'static-website/static-website'
  TemplateVersion:
    Description: 'cloudonaut.io template version.'
    Value: '__VERSION__'
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  URL:
    Description: 'URL to static website.'
    Value: !Sub 'https://${DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-URL'
