---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC: private DNS zone, a cloudonaut.io template'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack
    - Label:
        default: 'Zone Parameters'
      Parameters:
      - Name
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Name:
    Description: 'The name of the domain (hosted zone).'
    Type: String
Resources:
  HostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: !Sub "${Name} private DNS zone"
      Name: !Ref Name
      VPCs:
      - VPCId:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
        VPCRegion: !Ref 'AWS::Region'
Outputs:
  TemplateID:
    Description: 'Template id'
    Value: 'vpc/zone-private'
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
  HostedZoneName:
    Description: 'The name of the hosted zone.'
    Value: !Ref Name
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneName'
  HostedZoneId:
    Description: 'The ID of the hosted zone.'
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
